platform :ios, '13.0'

target 'WebRTCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCDemo

  pod 'WebRTC-SDK', '=137.7151.11'
  pod 'Socket.IO-Client-Swift', '16.1.0'

end